name: Energy Insights Platform CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/ingestion/**'
      - 'backend/analytics/**'
      - 'frontend/**'
      - 'docker-compose*.yml'
      - 'nginx/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'backend/ingestion/**'
      - 'backend/analytics/**'
      - 'frontend/**'
      - 'docker-compose*.yml'
      - 'nginx/**'

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      ingestion: ${{ steps.filter.outputs.ingestion }}
      analytics: ${{ steps.filter.outputs.analytics }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ingestion:
              - 'backend/ingestion/**'

            analytics:
              - 'backend/analytics/**'

            frontend:
              - 'frontend/**'

  test-ingestion:
    needs: changes
    if: ${{ needs.changes.outputs.ingestion == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend/ingestion
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest pytest-mock

      - name: Run Tests
        run: |
          cd backend/ingestion
          python -m pytest


  test-analytics:
    needs: changes
    if: ${{ needs.changes.outputs.analytics == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper Executable
        run: chmod +x backend/analytics/mvnw

      - name: Build and Run Tests
        run: |
          cd backend/analytics
          ./mvnw clean test
